### ISSUE TITLE
AtExit can't be found

### ISSUE THREAD

**Issue by yhyu13** [NotCookey/Rainy#1]
Hi, I am running with Python3.10.5. The install requirement would fail on atExit module. After I removed it from requirement, it runs fine.

**Comment by NotCookey** [comment]
> Hi, I am running with Python3.10.5. The install requirement would fail on atExit module. After I removed it from requirement, it runs fine.

Hello, So i've tested it on the Py 10.5 and it certainly does work without needing to install atexit. I was using an old python 3 version for the project so i had to install it manually but seems like the latest python versions already has it included. Thanks for informing about it! I'll remove it from the requirements and might add some steps in the readme if they are having trouble with `atexit` module
